-- AlterTable
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "kind" TEXT NOT NULL DEFAULT 'product';
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "outfitSlots" JSONB;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "compareAtPrice" DOUBLE PRECISION;
