ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "cargoCarrier" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "cargoCarrierId" INTEGER;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "cargoPostNumber" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "cargoTrackingUrl" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "cargoBarcodeUrl" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "cargoDesi" DOUBLE PRECISION;
